Vagrant.configure("2") do |config|
  config.vm.define "python" do |python|
     python.vm.box = "ubuntu/bionic64"
     python.vm.provision "shell", inline: <<-SHELL
         apt-get update
         apt-get install software-properties-common -y
	     add-apt-repository ppa:deadsnakes/ppa -y
	     apt-get update
	     apt-get install python3 python3-pip python3-dev libpq-dev -y
         pip3 install psycopg2 Django
    SHELL
	python.vm.provision "file", source: "./empty_file", destination: "~/empty_file"
   end
end
